
<VictoryPopup>
    AnchorLayout:
        id: victoryLayout
        anchor_x: 'center'
        anchor_y: 'center'
        pos_hint: {'x': 0, 'top': 1}
        GridLayout:
            cols: 1
            Label:
                text: "Victory"
                font_size: 50
            Label:
                id: victoryPuntenLabel
                text: "Punten: 0"
                font_size: 45
            Label:
                text: "Restart in 5"
                font_size: 40
